name: Apply patches

on:
  workflow_call:

jobs:
  apply-patches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up UV for build
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true

      - name: Install Build Dependencies
        run: |
          uv sync --dev

      - name: Clone Browser Use Version
        run: |
          git clone https://github.com/browser-use/browser-use --branch 0.9.3

      - name: Apply Python Patch
        run: |
          cp -r ./src/browser-use/. ./browser-use
          cp README.md ./browser-use/README.md
          python patch-re-browser-use.py

      - name: Upload Patched Browser Use
        uses: actions/upload-artifact@v4
        with:
          name: browser-use
          path: browser-use
