name: package
on:
#  push:
#    branches:
#      - main
#      - stable
#      - 'releases/**'
#    tags:
#      - '*'
#  pull_request:
  workflow_dispatch:

# These two jobs check the building process (uv build) and that the generated *.whl is usable
# I don't think I will need them. They are here just in case
jobs:
  call-apply-patches:
    uses: ./.github/workflows/apply-patches.yaml

  build:
    needs:
      - call-apply-patches
    name: pip-build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: browser-use
    steps:
      - name: Download Patched Browser Use
        uses: actions/download-artifact@v4
        with:
          name: browser-use
          path: browser-use
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
          # Explicitly setting where to create .venv directory ...
          working-directory: browser-use
      - run: uv build --python 3.12
      - uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: |
            dist/*.whl
            dist/*.tar.gz

  build_test:
    name: pip-install-on-${{ matrix.os }}-py-${{ matrix.python-version }}
    needs: build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: browser-use
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    env:
      ANONYMIZED_TELEMETRY: 'false'

    steps:
      - name: Download Patched Browser Use
        uses: actions/download-artifact@v4
        with:
          name: browser-use
          path: browser-use
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
          # Explicitly setting where to create .venv directory ...
          working-directory: browser-use
      - uses: actions/download-artifact@v4
        with:
          name: dist-artifact

      - name: Set up venv and test for OS/Python versions
        shell: bash
        run: |
          uv venv /tmp/testenv --python ${{ matrix.python-version }}
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            . /tmp/testenv/Scripts/activate
          else
            source /tmp/testenv/bin/activate
          fi
          uv pip install *.whl
          python -c 'from browser_use import Agent, Browser, Controller, ActionModel, ActionResult'
